##Email配置
email:
  host-name: smtp.163.com #服务地址，可以直接在web端登录，找到smtp服务看到，163邮箱默认开放25端口，可暂时不设置
  authentication:
    username: darenzai@163.com
    password: BBJJZDBYDYIIBHZA #手动的设置令牌
  form:
    mail: darenzai@163.com #发送方，必须为你设置的username一致
    name: darenzai #发送方显示的名称，可以随意设置
  charset: UTF-8 #编码格式，一般设置为UTF-8
